#!/bin/sh

#
# simply lists the commands to process all rda files
# use `convert_all | sh` to run the commands
#

set -e

./listFiles | grep -v nfo |\
awk 'NR>1{
  inp = $4
  gsub("rda", "csv.gz", $4)
  outp = $4

  printf"./rda2csv.R %s %s\n",inp,outp

}'
